// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: events/task_events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	TaskId        int32                  `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskText      string                 `protobuf:"bytes,4,opt,name=task_text,json=taskText,proto3" json:"task_text,omitempty"`
	TaskStatus    string                 `protobuf:"bytes,5,opt,name=task_status,json=taskStatus,proto3" json:"task_status,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_events_task_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_task_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_events_task_events_proto_rawDescGZIP(), []int{0}
}

func (x *TaskEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TaskEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TaskEvent) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskEvent) GetTaskText() string {
	if x != nil {
		return x.TaskText
	}
	return ""
}

func (x *TaskEvent) GetTaskStatus() string {
	if x != nil {
		return x.TaskStatus
	}
	return ""
}

func (x *TaskEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TaskEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_events_task_events_proto protoreflect.FileDescriptor

const file_events_task_events_proto_rawDesc = "" +
	"\n" +
	"\x18events/task_events.proto\x12\x06events\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x01\n" +
	"\tTaskEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\x05R\x06taskId\x12\x1b\n" +
	"\ttask_text\x18\x04 \x01(\tR\btaskText\x12\x1f\n" +
	"\vtask_status\x18\x05 \x01(\tR\n" +
	"taskStatus\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB#Z!notification-service/proto/eventsb\x06proto3"

var (
	file_events_task_events_proto_rawDescOnce sync.Once
	file_events_task_events_proto_rawDescData []byte
)

func file_events_task_events_proto_rawDescGZIP() []byte {
	file_events_task_events_proto_rawDescOnce.Do(func() {
		file_events_task_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_task_events_proto_rawDesc), len(file_events_task_events_proto_rawDesc)))
	})
	return file_events_task_events_proto_rawDescData
}

var file_events_task_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_task_events_proto_goTypes = []any{
	(*TaskEvent)(nil),             // 0: events.TaskEvent
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_events_task_events_proto_depIdxs = []int32{
	1, // 0: events.TaskEvent.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_events_task_events_proto_init() }
func file_events_task_events_proto_init() {
	if File_events_task_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_task_events_proto_rawDesc), len(file_events_task_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_task_events_proto_goTypes,
		DependencyIndexes: file_events_task_events_proto_depIdxs,
		MessageInfos:      file_events_task_events_proto_msgTypes,
	}.Build()
	File_events_task_events_proto = out.File
	file_events_task_events_proto_goTypes = nil
	file_events_task_events_proto_depIdxs = nil
}
